'use client';

import { useEffect, useMemo, useState } from 'react';
import { AirplaneTakeoff, CalendarDots, CheckCircle, CircleNotch, Envelope, FileArrowDown, Plus, Trash, WarningCircle, X } from '@phosphor-icons/react';
import DraggableShift from '@/components/DraggableShift';
import StaffSettings from '@/components/StaffSettings';
import { formatTime12 } from '@/lib/date-utils';
import { Button } from '@/components/ui/Button';
import { EmptyState, LoadingState } from '@/components/ui/DataState';
import { Metric } from '@/components/ui/Metric';
import { PageHeader } from '@/components/ui/PageHeader';
import { Panel } from '@/components/ui/Panel';

interface Shift { staffName: string; start: string; end: string; hours: number; coversPeaks: string[] }
interface FlightDetail { flight_num: string; scheduled_time: string; flight_type: string; estimated_passengers: number }
interface DaySchedule { date: string; shifts: Shift[]; coverageScore: number; flightCount?: number; dayOff?: string; flights?: FlightDetail[] }
interface ScheduleData {
  success: boolean; scheduleDate: string; scheduleDateEnd?: string; schedule?: Shift[]; coverageScore?: number; totalHours?: number;
  schedules?: DaySchedule[]; averageCoverage?: number; nichelleDays?: number; bilianaDays?: number;
  staffHours?: Record<string, { totalHours: number; daysWorked: number }>; nichelleTarget?: number; nichelleOnTarget?: boolean; briefing: string;
}

const staffColors: Record<string, { bg: string; border: string; bar: string; text: string }> = {
  Biliana: { bg: 'bg-accent/15', border: 'border-accent', bar: 'bg-accent', text: 'text-ink' },
  Nichelle: { bg: 'bg-positive/10', border: 'border-positive', bar: 'bg-positive', text: 'text-ink' },
};
const fallbackColor = { bg: 'bg-app-bg', border: 'border-line', bar: 'bg-muted', text: 'text-ink' };

function asDays(data: ScheduleData): DaySchedule[] {
  if (data.schedules) return data.schedules;
  return data.schedule ? [{ date: data.scheduleDate, shifts: data.schedule, coverageScore: data.coverageScore ?? 0 }] : [];
}
function addDays(date: string, amount: number) { const result = new Date(`${date}T12:00:00`); result.setDate(result.getDate() + amount); return result.toISOString().slice(0, 10); }
function displayDate(date: string) { return new Date(`${date}T12:00:00`).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' }); }
function timeToMinutes(value: string) { const [hours, minutes] = value.split(':').map(Number); return hours * 60 + minutes; }
function minutesToTime(value: number) { return `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`; }
function timelinePosition(value: string) { return Math.max(0, Math.min(100, ((timeToMinutes(value) - 540) / 660) * 100)); }
function totalsFor(days: DaySchedule[]) { const totals: Record<string, { totalHours: number; daysWorked: number }> = {}; for (const day of days) for (const shift of day.shifts) { const total = totals[shift.staffName] ?? { totalHours: 0, daysWorked: 0 }; total.totalHours = Math.round((total.totalHours + shift.hours) * 10) / 10; total.daysWorked += 1; totals[shift.staffName] = total; } return totals; }

function AddStaff({ assigned, onAdd }: { assigned: Set<string>; onAdd: (name: string) => void }) {
  const [open, setOpen] = useState(false); const [staff, setStaff] = useState<{ name: string; role: string }[]>([]);
  const load = async () => { if (!staff.length) { try { const response = await fetch('/api/staff'); const payload = await response.json(); setStaff((payload.staff ?? []).filter((item: { is_active: boolean }) => item.is_active)); } catch { return; } } setOpen(value => !value); };
  const available = staff.filter(item => !assigned.has(item.name));
  return <div className="relative"><Button size="sm" variant="ghost" onClick={() => void load()}><Plus size={15} />Add staff</Button>{open ? <div className="absolute right-0 z-20 mt-1 min-w-48 rounded-md border border-line bg-surface p-1 shadow-lg">{available.length ? available.map(item => <button className="terminal-focus flex w-full items-center justify-between rounded-sm px-3 py-2 text-left text-sm hover:bg-app-bg" key={item.name} onClick={() => { onAdd(item.name); setOpen(false); }}><span className="font-semibold text-ink">{item.name}</span><span className="text-xs text-muted">{item.role}</span></button>) : <p className="px-3 py-2 text-xs text-muted">All active staff are assigned.</p>}</div> : null}</div>;
}

export default function SchedulesPage() {
  const [scheduleDate, setScheduleDate] = useState(() => { const date = new Date(); date.setDate(date.getDate() - date.getDay() + 1); return date.toISOString().slice(0, 10); });
  const scheduleDateEnd = useMemo(() => addDays(scheduleDate, 13), [scheduleDate]);
  const [scheduleData, setScheduleData] = useState<ScheduleData | null>(null);
  const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [error, setError] = useState('');
  const [emailAddress, setEmailAddress] = useState(''); const [emailing, setEmailing] = useState(false); const [emailSent, setEmailSent] = useState(false); const [emailError, setEmailError] = useState('');

  useEffect(() => { let active = true; setLoading(true); fetch(`/api/schedules/latest?startDate=${scheduleDate}&endDate=${scheduleDateEnd}`).then(async response => response.ok ? response.json() : null).then(payload => { if (active && payload?.exists) setScheduleData(payload); }).catch(() => undefined).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [scheduleDate, scheduleDateEnd]);
  const report = (message: string) => { setError(message); window.setTimeout(() => setError(''), 5000); };
  const generateSchedule = async () => { setGenerating(true); setError(''); try { const response = await fetch('/api/schedules/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scheduleDate, scheduleDateEnd, staff: [{ name: 'Biliana', availableStart: '09:00', availableEnd: '20:00', maxHours: 8 }, { name: 'Nichelle', availableStart: '09:00', availableEnd: '20:00', maxHours: 8 }] }) }); const payload = await response.json(); if (!response.ok || payload.error) report(payload.error ?? 'Failed to generate schedule.'); else setScheduleData(payload); } catch { report('Failed to generate schedule. Please try again.'); } finally { setGenerating(false); } };
  const clearSchedule = async () => { if (!window.confirm('Clear this schedule? You can regenerate it anytime.')) return; try { const response = await fetch('/api/schedules/clear', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ startDate: scheduleDate, endDate: scheduleDateEnd }) }); if (!response.ok) throw new Error(); setScheduleData(null); } catch { report('Failed to clear schedule.'); } };
  const saveShift = async (date: string, staffName: string, start: string, end: string) => { if (!scheduleData) return; const old = scheduleData; const schedules = asDays(old).map(day => day.date === date ? { ...day, shifts: day.shifts.map(shift => shift.staffName === staffName ? { ...shift, start, end, hours: Math.round((timeToMinutes(end) - timeToMinutes(start)) / 6) / 10 } : shift) } : day); const staffHours = totalsFor(schedules); const target = Math.ceil(schedules.length / 7) * 40; setScheduleData({ ...old, schedules, staffHours, nichelleTarget: target, nichelleOnTarget: Math.abs((staffHours.Nichelle?.totalHours ?? 0) - target) <= 2 }); try { const response = await fetch('/api/schedules/shift', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ date, staffName, start, end }) }); if (!response.ok) throw new Error(); } catch { setScheduleData(old); report('Failed to save shift change. Your edit was reverted.'); } };
  const changeStaffing = async (date: string, staffName: string, remove = false) => { if (!scheduleData) return; const old = scheduleData; const schedules = asDays(old).map(day => day.date !== date ? day : { ...day, shifts: remove ? day.shifts.filter(shift => shift.staffName !== staffName) : [...day.shifts, { staffName, start: '10:00', end: '15:00', hours: 5, coversPeaks: [] }] }); setScheduleData({ ...old, schedules, staffHours: totalsFor(schedules) }); try { const response = await fetch('/api/schedules/shift', { method: remove ? 'DELETE' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(remove ? { date, staffName } : { date, staffName, start: '10:00', end: '15:00' }) }); if (!response.ok) throw new Error(); } catch { setScheduleData(old); report(`Failed to ${remove ? 'remove' : 'add'} shift. Your change was reverted.`); } };
  const sendEmail = async () => { if (!emailAddress || !scheduleData) return; setEmailing(true); setEmailError(''); try { const response = await fetch('/api/schedules/notify', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ startDate: scheduleDate, endDate: scheduleDateEnd, recipientEmail: emailAddress }) }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error ?? 'Unable to send email.'); setEmailSent(true); window.setTimeout(() => setEmailSent(false), 5000); } catch (caught) { setEmailError(caught instanceof Error ? caught.message : 'Unable to send email.'); } finally { setEmailing(false); } };
  const days = scheduleData ? asDays(scheduleData) : [];
  const coverage = scheduleData ? (scheduleData.schedules ? scheduleData.averageCoverage ?? 0 : scheduleData.coverageScore ?? 0) : 0;

  return <main className="mx-auto w-full max-w-[1440px] space-y-6 px-4 py-6 sm:px-6 lg:px-8">
    <PageHeader eyebrow="Labour control" title="Schedules" description="Build a two-week staffing plan from passenger demand, then adjust the operational details on the board." metadata={<span className="font-mono text-xs">09:00–20:00 · 30-minute edits</span>} actions={<><label className="flex min-h-11 items-center gap-2 rounded-md border border-line bg-surface px-3 text-sm font-medium text-ink"><CalendarDots size={18} aria-hidden="true" /><span className="sr-only">Schedule start</span><input aria-label="Schedule start" className="w-32 bg-transparent font-mono text-sm outline-none" type="date" value={scheduleDate} onChange={event => setScheduleDate(event.target.value)} /></label><Button onClick={() => void generateSchedule()} disabled={generating}>{generating ? <CircleNotch className="animate-spin" size={18} /> : null}{generating ? 'Building schedule' : scheduleData ? 'Regenerate plan' : 'Generate plan'}</Button></>} />
    <Panel title="Planning window" description={`${displayDate(scheduleDate)} — ${displayDate(scheduleDateEnd)} · A fixed 14-day cycle.`} actions={scheduleData ? <Button variant="danger" size="sm" onClick={() => void clearSchedule()}><Trash size={16} />Clear plan</Button> : undefined}><StaffSettings /></Panel>
    {error ? <div className="flex gap-3 rounded-md border-l-4 border-danger bg-surface p-4 text-sm text-ink" role="alert"><WarningCircle className="shrink-0 text-danger" size={20} />{error}</div> : null}
    {loading ? <LoadingState label="Loading saved schedule" /> : null}
    {!loading && !scheduleData ? <EmptyState title="No schedule for this planning window" message="Generate a plan to match shifts with departures, passenger volume, and store hours." actionLabel="Generate plan" onAction={() => void generateSchedule()} /> : null}
    {scheduleData ? <>
      <section className="grid gap-5 border-y border-line py-5 sm:grid-cols-3"><Metric label="Coverage confidence" value={`${coverage}%`} tone={coverage >= 90 ? 'positive' : coverage >= 70 ? 'warning' : 'danger'} detail="Demand windows covered" /><Metric label="Days scheduled" value={days.length} detail="Two-week planning cycle" /><Metric label="Staffed shifts" value={days.reduce((count, day) => count + day.shifts.length, 0)} detail="Drag a bar to adjust times" /></section>
      <Panel title="Shift board" description="Each line is one staff assignment. Drag bars or use the handles to make 30-minute changes."><div className="overflow-x-auto"><div className="min-w-[720px] space-y-6"><div className="grid grid-cols-[9rem_1fr] gap-3 border-b border-line pb-2 text-xs font-mono text-muted"><span>Assignment</span><div className="flex justify-between"><span>09:00</span><span>11:00</span><span>13:00</span><span>15:00</span><span>17:00</span><span>20:00</span></div></div>{days.map(day => <ScheduleDay key={day.date} day={day} onUpdate={saveShift} onRemove={name => void changeStaffing(day.date, name, true)} onAdd={name => void changeStaffing(day.date, name)} />)}</div></div></Panel>
      {scheduleData.briefing ? <Panel title="Staffing brief" description="Generated operational handoff"><p className="max-w-4xl whitespace-pre-wrap text-sm leading-6 text-ink">{scheduleData.briefing}</p></Panel> : null}
      {scheduleData.staffHours ? <Panel title="Hours ledger" description="Two-week staff totals and target check."><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(scheduleData.staffHours).map(([name, stats]) => { const target = name === 'Nichelle' ? scheduleData.nichelleTarget : undefined; const withinTarget = name !== 'Nichelle' || scheduleData.nichelleOnTarget; return <Metric key={name} label={name} value={`${stats.totalHours}h`} detail={`${stats.daysWorked} days${target ? ` · ${withinTarget ? 'target met' : `target ${target}h`}` : ''}`} tone={withinTarget ? 'positive' : 'warning'} />; })}</div></Panel> : null}
      <Panel title="Share the schedule" description="Export the editable schedule or send the current plan to a manager."><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><a className="terminal-focus inline-flex min-h-11 items-center justify-center gap-2 rounded-md border border-line bg-surface px-4 text-sm font-semibold text-ink hover:bg-app-bg" href={`/api/schedules/export?startDate=${scheduleDate}&endDate=${scheduleDateEnd}`}><FileArrowDown size={17} />Export Excel</a><div className="min-w-0 flex-1"><label className="mb-1 block text-xs font-semibold tracking-[0.04em] text-muted uppercase" htmlFor="schedule-recipient">Recipient email</label><input className="terminal-focus min-h-11 w-full rounded-md border border-line bg-surface px-3 text-sm text-ink" id="schedule-recipient" type="email" value={emailAddress} onChange={event => setEmailAddress(event.target.value)} placeholder="manager@example.com" /></div><Button onClick={() => void sendEmail()} disabled={emailing || !emailAddress}>{emailing ? <CircleNotch className="animate-spin" size={18} /> : <Envelope size={18} />}{emailing ? 'Sending' : 'Email schedule'}</Button></div>{emailSent ? <p className="mt-3 flex items-center gap-2 text-sm text-positive"><CheckCircle size={18} />Schedule sent.</p> : null}{emailError ? <p className="mt-3 text-sm text-danger" role="alert">{emailError}</p> : null}</Panel>
    </> : null}
  </main>;
}

function ScheduleDay({ day, onUpdate, onRemove, onAdd }: { day: DaySchedule; onUpdate: (date: string, name: string, start: string, end: string) => Promise<void>; onRemove: (name: string) => void; onAdd: (name: string) => void }) {
  const assigned = new Set(day.shifts.map(shift => shift.staffName));
  const departures = day.flights?.filter(flight => flight.flight_type === 'departure') ?? [];
  return <article className="border-b border-line pb-5 last:border-0 last:pb-0"><header className="mb-3 flex items-center justify-between gap-3"><div><h3 className="font-display text-lg font-semibold text-ink">{displayDate(day.date)}</h3><p className="mt-0.5 text-xs text-muted">{day.flightCount ?? departures.length} flights · {day.coverageScore}% coverage{day.dayOff ? ` · ${day.dayOff} off` : ''}</p></div><AddStaff assigned={assigned} onAdd={onAdd} /></header><div className="space-y-2">{day.shifts.map(shift => <div className="group grid grid-cols-[9rem_1fr] items-center gap-3" key={`${day.date}-${shift.staffName}`}><div className="flex min-w-0 items-center gap-2"><button aria-label={`Remove ${shift.staffName} from ${displayDate(day.date)}`} className="terminal-focus rounded-sm p-1 text-muted opacity-0 transition-opacity hover:text-danger group-hover:opacity-100 focus:opacity-100" onClick={() => onRemove(shift.staffName)}><X size={15} /></button><span className="truncate text-sm font-semibold text-ink">{shift.staffName}</span></div><DraggableShift staffName={shift.staffName} start={shift.start} end={shift.end} color={staffColors[shift.staffName] ?? fallbackColor} timeToPercent={timelinePosition} onUpdate={(start, end) => void onUpdate(day.date, shift.staffName, start, end)} /></div>)}{departures.length ? <div className="grid grid-cols-[9rem_1fr] items-center gap-3 pt-1"><span className="text-xs font-semibold tracking-[0.04em] text-muted uppercase">Departures</span><div className="relative h-7 border-t border-dashed border-line">{departures.map(flight => { const local = flight.scheduled_time.slice(11, 16); const shopTime = minutesToTime(timeToMinutes(local) - 30); const position = timelinePosition(shopTime); const covered = day.shifts.some(shift => timeToMinutes(shopTime) >= timeToMinutes(shift.start) && timeToMinutes(shopTime) < timeToMinutes(shift.end)); return position <= 0 || position >= 100 ? null : <span key={flight.flight_num} title={`${flight.flight_num}: shop window ${formatTime12(shopTime)} · ${flight.estimated_passengers} passengers`} className={`absolute top-1 inline-flex h-5 w-5 -translate-x-1/2 items-center justify-center rounded-full border ${covered ? 'border-positive bg-positive/15 text-positive' : 'border-danger bg-danger/10 text-danger'}`} style={{ left: `${position}%` }}><AirplaneTakeoff size={11} /></span>; })}</div></div> : null}</div></article>;
}
